# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailcore', '0033_make_first_published_at_editable'),
    ]

    operations = [
    ]
